# Use an official Python runtime as a parent image
FROM python:3.11

# Set environment variables
# Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1
# Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /usr/src/app

# Install dependencies
# Copy the Pipfile and Pipfile.lock into the container at /usr/src/app/
COPY Pipfile Pipfile.lock /usr/src/app/
# Install pipenv and dependencies
RUN pip install --upgrade pip && pip install pipenv && pipenv install --dev --system

# Copy the current directory contents into the container at /usr/src/app/
COPY . /usr/src/app/

RUN chmod +x /usr/src/app/entrypoint.sh

# Run the application on port 8000
EXPOSE 8000

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
