# Generated by Django 4.1.7 on 2023-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_picture_height_profile_picture_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture_width',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile-pic.png', upload_to='profile_pictures/'),
        ),
    ]
