# Generated by Django 4.1.7 on 2023-03-14 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='bug',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL),
        ),
    ]
